#!/bin/bash
IMMICH_PATH=/var/lib/immich
cat <<EOF_INITIALIZE_SERVICES_SCRIPT > $IMMICH_PATH/Extras/ImmichInitializeServices.sh
echo "Creating .service files in /etc/systemd/system"

cat <<EOF_MACHINE_LEARNING > /etc/systemd/system/immich-machine-learning.service
[Unit]
Description=immich machine-learning
Documentation=https://github.com/immich-app/immich

[Service]
User=immich
Group=immich
Type=simple
Restart=on-failure
UMask=0077

WorkingDirectory=/var/lib/immich/app
EnvironmentFile=/var/lib/immich/env
ExecStart=/var/lib/immich/app/machine-learning/start.sh

SyslogIdentifier=immich-machine-learning
StandardOutput=append:/var/log/immich/immich-machine-learning.log
StandardError=append:/var/log/immich/immich-machine-learning.log

[Install]
WantedBy=multi-user.target
EOF_MACHINE_LEARNING

echo "Created /etc/systemd/system/immich-machine-learning.service"


cat <<EOF_IMMICH > /etc/systemd/system/immich.service
[Unit]
Description=immich server
Documentation=https://github.com/immich-app/immich
Requires=redis-server.service
Requires=postgresql.service
Requires=immich-machine-learning.service

[Service]
User=immich
Group=immich
Type=simple
Restart=on-failure
UMask=0077

WorkingDirectory=/var/lib/immich/app
EnvironmentFile=/var/lib/immich/env
ExecStart=node /var/lib/immich/app/dist/main

SyslogIdentifier=immich
StandardOutput=append:/var/log/immich/immich.log
StandardError=append:/var/log/immich/immich.log

[Install]
WantedBy=multi-user.target
EOF_IMMICH

echo "Created /etc/systemd/system/immich.service"

echo "Reload Daemons"
sudo systemctl daemon-reload

echo "Enable and Activate Services"

sudo systemctl enable immich-microservices.service&&systemctl enable immich-machine-learning.service&&systemctl enable immich.service

sudo systemctl restart immich-machine-learning&&systemctl restart immich
sudo chmod 644 /var/log/immich/*.log
sudo systemctl status immich*
EOF_INITIALIZE_SERVICES_SCRIPT

echo "Install Services If Needed"
echo "sudo sh $IMMICH_PATH/Extras/ImmichInitializeServices.sh"
